-- MySQL Script generated by MySQL Workbench
-- Fri Jan  9 09:15:27 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kategorie` (
  `idkategorie:` INT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idkategorie:`),
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`polozka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`polozka` (
  `idpolozka` INT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(100) NOT NULL,
  `datum_expirace` DATE NOT NULL,
  `pocet_kusu` INT NOT NULL,
  `id_kategorie` INT NULL,
  `kategorie_idkategorie:` INT NOT NULL,
  PRIMARY KEY (`idpolozka`, `kategorie_idkategorie:`),
  INDEX `fk_polozka_kategorie_idx` (`kategorie_idkategorie:` ASC) ,
  CONSTRAINT `fk_polozka_kategorie`
    FOREIGN KEY (`kategorie_idkategorie:`)
    REFERENCES `mydb`.`kategorie` (`idkategorie:`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
